#!/usr/bin/env python3
"""Splice tools/static-head.html into the outer <head> of index.html.

The site is exported from Claude Design as a single compiled index.html. The
bundler owns the outer <head> and emits only a charset, title, style and
noscript block; everything declared in the design source is inlined into the
JavaScript bundle, where social scrapers -- which do not execute JS -- never
see it. This re-inserts the tags as literal HTML inside <head>.

Run after every export. Idempotent: re-running replaces the block rather than
duplicating it, and it strips blocks left by Claude Design's own injection or
by earlier hand-patches.

    python tools/apply_static_head.py            # patch + verify index.html
    python tools/apply_static_head.py --check    # verify only, change nothing
"""

import argparse
import io
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGET = ROOT / "index.html"
SOURCE = ROOT / "tools" / "static-head.html"

BEGIN = "<!-- static-head:begin -- generated by tools/apply_static_head.py; edit tools/static-head.html -->"
END = "<!-- static-head:end -->"

# Our own block, plus surrounding whitespace, so repeat runs do not drift.
MARKED = re.compile(
    r"\n?[ \t]*" + re.escape(BEGIN) + r".*?" + re.escape(END) + r"[ \t]*",
    re.DOTALL,
)

# Blocks written by other tooling. Claude Design has used more than one marker
# style, so match the family rather than one exact string.
FOREIGN = [
    re.compile(r"\n?[ \t]*<!--\s*om:static-head.*?om:static-head[^>]*-->[ \t]*", re.DOTALL),
    re.compile(
        r"\n?[ \t]*<!--\s*static head tags:.*?-->.*?<link rel=\"apple-touch-icon\"[^>]*>[ \t]*",
        re.DOTALL,
    ),
]

CHARSET = re.compile(r"<meta\s+charset=[\"']?[^>\"']+[\"']?\s*/?>", re.IGNORECASE)
TAG = re.compile(r"<(?:meta|link)\b[^>]*>")


def read(path):
    return io.open(path, encoding="utf-8").read()


def tags():
    return [ln.strip() for ln in read(SOURCE).splitlines() if ln.strip()]


def build_block():
    body = "\n".join("  " + t for t in tags())
    return "\n  " + BEGIN + "\n" + body + "\n  " + END


def outer_head(html):
    """Everything inside <head>...</head>.

    Cutting at the first <script> is NOT equivalent: a block placed after
    </head> but before the first script would pass, and tags in <body> are
    ignored by scrapers. A 2026-09-08 export made exactly that mistake.
    """
    start = html.lower().find("<head")
    end = html.lower().find("</head>")
    if start == -1 or end == -1:
        return ""
    return html[start:end]


def foreign_blocks(html):
    """Tags from another tool's block, so we can report copy drift."""
    found = []
    for pat in FOREIGN:
        for m in pat.finditer(html):
            found.extend(TAG.findall(m.group(0)))
    return found


def strip_existing(html):
    html = MARKED.sub("", html)
    for pat in FOREIGN:
        html = pat.sub("", html)
    return html


def verify(html):
    head = outer_head(html)
    problems = ["missing from outer <head>: " + t[:70] for t in tags() if t not in head]
    if '\\"' in head:
        problems.append("escaped quotes in <head> -- tags are inside a JS string")
    for name in ("og:image", "og:title", "twitter:card"):
        if name in html and name not in head:
            problems.append(name + " appears in the document but NOT inside <head>")
    return problems


def report_drift(export_tags):
    """Warn when the export's own tags differ from our source of truth."""
    ours = set(tags())
    theirs = set(export_tags)
    if not theirs:
        return
    only_theirs = [t for t in export_tags if t not in ours]
    if only_theirs:
        print("\nNOTE: the export's tags differ from tools/static-head.html.")
        print("      Ours win. If the export is newer, sync static-head.html:")
        for t in only_theirs:
            print("      export: " + t[:100])


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="verify only; do not modify")
    args = ap.parse_args()

    for p in (TARGET, SOURCE):
        if not p.exists():
            sys.exit("ERROR: " + str(p) + " not found")

    drift = []
    if not args.check:
        original = read(TARGET)
        drift = foreign_blocks(original)
        html = strip_existing(original)
        m = CHARSET.search(outer_head(html))
        if not m:
            sys.exit("ERROR: no <meta charset> inside <head> -- export format changed")
        html = html[: m.end()] + build_block() + html[m.end():]
        io.open(TARGET, "w", encoding="utf-8", newline="").write(html)
        print("injected " + str(len(tags())) + " tags into <head> of " + TARGET.name)

    final = read(TARGET)
    problems = verify(final)
    if problems:
        print("VERIFY FAILED:", file=sys.stderr)
        for p in problems:
            print("  - " + p, file=sys.stderr)
        sys.exit(1)

    head_lines = outer_head(final).count("\n") + 1
    print("verified: all tags literal inside <head> (which ends at line %d)" % head_lines)
    report_drift(drift)


if __name__ == "__main__":
    main()
