#!/usr/bin/env python3
"""Splice tools/static-head.html into the outer <head> of index.html.

The site is exported from Claude Design as a single compiled index.html whose
outer <head> holds only a charset, title, style and noscript block. Every SEO
and Open Graph tag lives inside the JavaScript bundle, where social scrapers --
which do not execute JS -- never see it. This re-inserts them as literal HTML.

Run after every export. Idempotent: re-running replaces the block rather than
duplicating it, and it cleans up blocks left by earlier hand-patches.

    python tools/apply_static_head.py            # patch + verify index.html
    python tools/apply_static_head.py --check    # verify only, change nothing
"""

import argparse
import io
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGET = ROOT / "index.html"
SOURCE = ROOT / "tools" / "static-head.html"

BEGIN = "<!-- static-head:begin -- generated by tools/apply_static_head.py; edit tools/static-head.html -->"
END = "<!-- static-head:end -->"

# Our own block, plus any surrounding whitespace, so repeat runs do not drift.
MARKED = re.compile(
    r"\n?[ \t]*" + re.escape(BEGIN) + r".*?" + re.escape(END) + r"[ \t]*",
    re.DOTALL,
)

# Blocks written by earlier tooling, stripped so we never stack duplicates.
LEGACY_PATTERNS = [
    # the original hand-patch: an unterminated comment through the last link tag
    re.compile(
        r"\n?[ \t]*<!--[ ]*static head tags:.*?-->.*?<link rel=\"apple-touch-icon\"[^>]*>[ \t]*\n?",
        re.DOTALL,
    ),
    # Claude Design's own splice marker
    re.compile(r"\n?[ \t]*<!--[ ]*om:static-head.*?om:static-head[^>]*-->[ \t]*\n?", re.DOTALL),
]

CHARSET = re.compile(r"<meta\s+charset=[\"']?[^>\"']+[\"']?\s*/?>", re.IGNORECASE)


def read(path):
    return io.open(path, encoding="utf-8").read()


def tags():
    return [ln.strip() for ln in read(SOURCE).splitlines() if ln.strip()]


def build_block():
    body = "\n".join("  " + t for t in tags())
    return "\n  " + BEGIN + "\n" + body + "\n  " + END


def strip_existing(html):
    html = MARKED.sub("", html)
    for pat in LEGACY_PATTERNS:
        html = pat.sub("\n", html)
    return html


def head_of(html):
    """The outer head: everything up to the first <script>, where scrapers stop."""
    cut = html.lower().find("<script")
    return html[: cut if cut != -1 else len(html)]


def verify(html):
    """Confirm every tag is literal text in the outer head, not JS-escaped."""
    head = head_of(html)
    problems = ["missing from outer <head>: " + t[:70] for t in tags() if t not in head]
    if '\\"' in head:
        problems.append("escaped quotes in outer <head> -- tags are inside a JS string")
    return problems


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="verify only; do not modify")
    args = ap.parse_args()

    for p in (TARGET, SOURCE):
        if not p.exists():
            sys.exit("ERROR: " + str(p) + " not found")

    if not args.check:
        html = strip_existing(read(TARGET))
        m = CHARSET.search(head_of(html))
        if not m:
            sys.exit("ERROR: no <meta charset> in the outer <head> -- export format changed")
        html = html[: m.end()] + build_block() + html[m.end():]
        io.open(TARGET, "w", encoding="utf-8", newline="").write(html)
        print("injected " + str(len(tags())) + " tags into " + TARGET.name)

    final = read(TARGET)
    problems = verify(final)
    if problems:
        print("VERIFY FAILED:", file=sys.stderr)
        for p in problems:
            print("  - " + p, file=sys.stderr)
        sys.exit(1)

    line = head_of(final).count("\n") + 1
    print("verified: all tags literal in outer <head>; first <script> at line " + str(line))


if __name__ == "__main__":
    main()
